-- LeetCode practice.
--
-- Two things have to be fixed before Rust is usable here.
--
-- The snippet LeetCode hands out is a fragment, not a program: no main, and
-- Solution, ListNode and TreeNode are never declared. rust-analyzer reports
-- them as missing types no matter how it is configured, which buries the
-- diagnostics that matter. The injector below supplies them. Injected code
-- lands outside the `@leet start` / `@leet end` markers, which is what the
-- plugin submits, so none of it reaches LeetCode.
--
-- The other half is that a lone .rs file in the storage directory is no cargo
-- project. rust-analyzer falls back to treating it as a cargo script, and cargo
-- then passes `-Z crate-attr=feature(frontmatter)` to a stable rustc, which
-- rejects it: "the option `Z` is only accepted on the nightly compiler",
-- followed by "Failed to discover workspace". Writing a Cargo.toml that lists
-- each solution as its own bin gives rust-analyzer a real workspace and cargo
-- something it can check. It is regenerated as solutions appear.

local storage = vim.fn.stdpath("data") .. "/leetcode"

-- Declarations LeetCode provides on its side but the downloaded snippet omits.
local preamble = {
  "pub struct Solution;",
  "",
  "#[derive(PartialEq, Eq, Clone, Debug)]",
  "pub struct ListNode {",
  "    pub val: i32,",
  "    pub next: Option<Box<ListNode>>,",
  "}",
  "",
  "impl ListNode {",
  "    #[inline]",
  "    fn new(val: i32) -> Self {",
  "        ListNode { next: None, val }",
  "    }",
  "}",
  "",
  "#[derive(Debug, PartialEq, Eq)]",
  "pub struct TreeNode {",
  "    pub val: i32,",
  "    pub left: Option<Rc<RefCell<TreeNode>>>,",
  "    pub right: Option<Rc<RefCell<TreeNode>>>,",
  "}",
  "",
  "impl TreeNode {",
  "    #[inline]",
  "    pub fn new(val: i32) -> Self {",
  "        TreeNode { val, left: None, right: None }",
  "    }",
  "}",
}

--- One bin target per solution file. Names come from the filename, which
--- contains dots and so cannot be a target name as is.
local function target_name(file)
  local stem = file:gsub("%.rs$", "")
  local name = stem:gsub("[^%w]+", "-"):gsub("^%-+", ""):gsub("%-+$", "")
  -- A target name may not start with a digit, and every file here does.
  if name:match("^%d") then
    name = "p" .. name
  end
  return name
end

local function write_manifest()
  if vim.fn.isdirectory(storage) == 0 then
    return
  end
  local files = vim.fn.readdir(storage, function(f)
    return f:match("%.rs$") ~= nil
  end)
  table.sort(files)
  if #files == 0 then
    return
  end

  local lines = {
    "# Generated by lua/plugins/leetcode.lua. Edits are overwritten.",
    "[package]",
    'name = "leetcode"',
    'version = "0.0.0"',
    -- 2021 rather than the 2024 cargo defaults to: the snippets are plain
    -- enough that the older edition avoids surprises, and nothing here needs
    -- 2024 features.
    'edition = "2021"',
    "",
    "# No src/ layout, so the automatic target discovery finds nothing.",
    "autobins = false",
    "autoexamples = false",
    "autotests = false",
    "autobenches = false",
    "",
  }
  for _, f in ipairs(files) do
    lines[#lines + 1] = "[[bin]]"
    lines[#lines + 1] = ('name = "%s"'):format(target_name(f))
    lines[#lines + 1] = ('path = "%s"'):format(f)
    lines[#lines + 1] = ""
  end

  local path = storage .. "/Cargo.toml"
  local existing = vim.fn.filereadable(path) == 1 and vim.fn.readfile(path) or {}
  if table.concat(existing, "\n") ~= table.concat(lines, "\n") then
    vim.fn.writefile(lines, path)
  end
end

return {
  {
    "kawre/leetcode.nvim",
    build = function()
      pcall(vim.cmd, "TSUpdate html")
    end,
    dependencies = {
      "nvim-telescope/telescope.nvim",
      "nvim-lua/plenary.nvim",
      "MunifTanjim/nui.nvim",
      "nvim-tree/nvim-web-devicons",
    },
    config = function(_, opts)
      require("leetcode").setup(opts)

      -- plenary.curl gives every request 10 seconds. A cross-border call to
      -- leetcode.com, especially one that lands on a Cloudflare check, runs
      -- past that often enough to matter, and when it does plenary raises from
      -- inside the job. Two things go wrong then: the failure arrives as a
      -- stack traceback rather than a message, and the traceback prints the
      -- whole curl command, LEETCODE_SESSION and csrftoken included. Those are
      -- live credentials and they end up in the message history.
      --
      -- Wrapping plenary rather than leetcode.api.utils: requiring the latter
      -- from here runs before setup has filled in config.storage, and its
      -- cookie module indexes that at load time.
      local curl = require("plenary.curl")
      for _, method in ipairs({ "get", "post", "put" }) do
        local uncaught = curl[method]
        curl[method] = function(a, b)
          -- plenary takes either (url, opts) or (opts)
          local o = type(a) == "table" and a or b
          local url = type(a) == "string" and a or (type(o) == "table" and o.url or nil)
          local ours = type(url) == "string" and url:match("leetcode%.") ~= nil
          if not ours then
            return uncaught(a, b)
          end
          if type(o) == "table" then
            o.timeout = o.timeout or 30000
          end
          local ok, res = pcall(uncaught, a, b)
          if ok then
            return res
          end
          -- Shaped so the plugin's own error handling can read it. Status 400
          -- rather than a 5xx on purpose: its retry check fires at 500 and
          -- would spend another five timeouts getting nowhere. exit stays 0
          -- because the check compares err.status without a nil guard, and the
          -- non-zero branch never sets one.
          return {
            exit = 0,
            status = 400,
            body = vim.json.encode({
              errors = { { message = "leetcode.com did not answer within 30s" } },
            }),
          }
        end
      end
    end,
    opts = {
      lang = "rust",
      injector = {
        rust = {
          -- The plugin assembles imports, then before, then the snippet, then
          -- after. #![allow] is an inner attribute and has to lead the file, so
          -- it goes here rather than in the preamble below.
          --
          -- Rc and RefCell are only needed by tree problems, but an unused
          -- import is quieter than a missing type, and the allow covers it.
          imports = {
            "#![allow(dead_code, unused_variables, unused_mut, unused_imports)]",
            "",
            "use std::rc::Rc;",
            "use std::cell::RefCell;",
            "use std::collections::*;",
          },
          before = preamble,
          -- Solutions have no entry point of their own.
          after = { "fn main() {}" },
        },
      },
    },
    init = function()
      local group = vim.api.nvim_create_augroup("leetcode_cargo", { clear = true })
      vim.api.nvim_create_autocmd({ "BufWritePost", "BufReadPost" }, {
        group = group,
        pattern = storage .. "/*.rs",
        callback = function()
          pcall(write_manifest)
        end,
      })
      vim.api.nvim_create_user_command("LeetCargo", function()
        write_manifest()
        vim.notify("LeetCargo: wrote " .. storage .. "/Cargo.toml", vim.log.levels.INFO)
      end, { desc = "Regenerate the LeetCode Cargo.toml" })
    end,
  },
}
